import { Platform, StyleSheet } from 'react-native';
import { theme } from '../theme/colors';

export const profileScreenStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: theme.yellow },
  screenFill: { flex: 1 },
  timeOverlayRoot: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 100,
    elevation: 100,
  },
  scroll: { flex: 1 },
  scrollContent: { padding: 12, paddingBottom: 32 },
  card: { borderRadius: 20, overflow: 'hidden', backgroundColor: theme.white, minHeight: 400 },
  yellow: { backgroundColor: theme.yellow, paddingVertical: 18, alignItems: 'center', position: 'relative' },
  screenTitle: { fontSize: 18, fontWeight: '800', color: theme.black },
  editBtn: { position: 'absolute', right: 16, top: 18, padding: 4 },
  loadingBox: { padding: 40, alignItems: 'center' },
  avatarRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, paddingTop: 20, gap: 16 },
  avatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: theme.yellow,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarTxt: { fontSize: 22, fontWeight: '900', color: theme.black },
  avatarMeta: { flex: 1 },
  displayName: { fontSize: 22, fontWeight: '900', color: theme.text },
  memberSince: { fontSize: 13, color: theme.textMuted, fontWeight: '600', marginTop: 4 },
  planBanner: {
    marginHorizontal: 16,
    marginTop: 20,
    padding: 16,
    backgroundColor: theme.offWhite,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.border,
  },
  planHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  planTitle: { fontSize: 14, fontWeight: '800', color: theme.textMuted, textTransform: 'uppercase', letterSpacing: 0.5 },
  planTier: { fontSize: 20, fontWeight: '900', color: theme.text, marginTop: 6 },
  planRenew: { fontSize: 14, color: theme.textMuted, marginTop: 6, fontWeight: '600', lineHeight: 20 },
  upgradeBannerBtn: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: theme.yellow,
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  upgradeBannerBtnFree: {
    borderColor: theme.black,
    shadowColor: theme.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  upgradeBannerBtnTxt: { fontSize: 15, fontWeight: '800', color: theme.black },
  sectionLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: theme.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginTop: 24,
    marginBottom: 10,
    marginHorizontal: 20,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: theme.border,
  },
  detailTextWrap: { flex: 1 },
  detailMuted: { fontSize: 12, fontWeight: '700', color: theme.textMuted, marginBottom: 2 },
  detailValue: { fontSize: 16, fontWeight: '700', color: theme.text },
  detailValueMono: { fontSize: 12, fontWeight: '600', color: theme.text, fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace' }) },
  upgradeOutline: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginHorizontal: 16,
    marginTop: 20,
    padding: 16,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: theme.black,
    backgroundColor: theme.white,
  },
  upgradeOutlineTxt: { flex: 1, fontSize: 16, fontWeight: '800', color: theme.black },
  outBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    marginHorizontal: 20,
    marginTop: 16,
    marginBottom: 24,
    backgroundColor: theme.yellow,
    paddingVertical: 14,
    borderRadius: 14,
  },
  outTxt: { fontSize: 16, fontWeight: '800', color: theme.black },
  fallback: { padding: 24, textAlign: 'center', color: theme.textMuted, fontWeight: '600' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalContent: { backgroundColor: theme.white, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, paddingBottom: 40 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 },
  modalTitle: { fontSize: 20, fontWeight: '900', color: theme.black },
  modalBody: { gap: 20 },
  inputGroup: { gap: 8 },
  inputLabel: { fontSize: 13, fontWeight: '800', color: theme.textMuted, textTransform: 'uppercase', marginLeft: 4 },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: theme.offWhite,
    paddingHorizontal: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.border,
  },
  input: { flex: 1, paddingVertical: 14, fontSize: 16, fontWeight: '700', color: theme.text },
  infoBox: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#f1f5f9', padding: 12, borderRadius: 12 },
  infoText: { fontSize: 13, fontWeight: '600', color: theme.textMuted },
  saveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: theme.yellow,
    paddingVertical: 16,
    borderRadius: 16,
    marginTop: 10,
  },
  saveBtnDisabled: { opacity: 0.6 },
  saveBtnTxt: { fontSize: 16, fontWeight: '900', color: theme.black },
  reminderCard: {
    marginHorizontal: 16,
    marginTop: 4,
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.offWhite,
    gap: 12,
  },
  reminderTopRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  reminderTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: theme.border,
  },
  reminderTextWrap: { flex: 1 },
  reminderHint: { fontSize: 12, color: theme.textMuted, fontWeight: '600', marginTop: 4 },
  reminderMessageBox: { gap: 8 },
  reminderScheduleInfo: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.textMuted,
    lineHeight: 18,
  },
  reminderTestBtn: {
    marginTop: 4,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.black,
    backgroundColor: theme.white,
    alignItems: 'center',
  },
  reminderTestBtnTxt: { fontSize: 14, fontWeight: '800', color: theme.black },
  reminderLinkBtn: { paddingVertical: 8, alignItems: 'center' },
  reminderLinkTxt: { fontSize: 12, fontWeight: '700', color: '#2563EB', textDecorationLine: 'underline' },
  batteryWarnRow: {
    backgroundColor: '#FFF7ED',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#FED7AA',
    padding: 10,
    gap: 4,
  },
  batteryWarnText: { fontSize: 12, fontWeight: '600', color: '#92400E', lineHeight: 18 },
  batteryWarnLink: { fontSize: 13, fontWeight: '800', color: '#EA580C' },
  reminderTextInput: {
    minHeight: 72,
    textAlignVertical: 'top',
    backgroundColor: theme.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.border,
    padding: 12,
    fontSize: 15,
    fontWeight: '600',
    color: theme.text,
  },
  timeModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  timeModalSheet: {
    backgroundColor: theme.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 12,
    paddingHorizontal: 8,
    paddingBottom: 28,
    alignItems: 'center',
  },
  timeModalDone: { alignItems: 'center', paddingVertical: 14 },
  timeModalDoneTxt: { fontSize: 17, fontWeight: '800', color: theme.black },
  inlinePickerWrap: {
    borderTopWidth: 1,
    borderTopColor: theme.border,
    alignItems: 'center',
    paddingTop: 4,
    paddingBottom: 4,
  },
  inlinePicker: { alignSelf: 'stretch', height: 200 },
  inlinePickerBtns: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 16,
    paddingBottom: 4,
    width: '100%',
    justifyContent: 'flex-end',
  },
  inlinePickerCancel: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.white,
  },
  inlinePickerCancelTxt: { fontSize: 15, fontWeight: '700', color: theme.textMuted },
  inlinePickerOk: {
    paddingVertical: 10,
    paddingHorizontal: 28,
    borderRadius: 10,
    backgroundColor: theme.yellow,
  },
  inlinePickerOkTxt: { fontSize: 15, fontWeight: '800', color: theme.black },
});
